/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
        "setState": () => any;
        "state": any;
    }
    interface AutoComplete {
        "label": string;
        "options": string;
        "required": boolean;
        "selected": string;
        "validate": () => Promise<boolean>;
    }
    interface FlexContainer {
        "gap": string;
    }
    interface TextInput {
        "label": string;
        "name": string;
        "required": boolean;
        "type": string;
        "validate": () => Promise<boolean>;
        "value": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAutoCompleteElement extends Components.AutoComplete, HTMLStencilElement {
    }
    var HTMLAutoCompleteElement: {
        prototype: HTMLAutoCompleteElement;
        new (): HTMLAutoCompleteElement;
    };
    interface HTMLFlexContainerElement extends Components.FlexContainer, HTMLStencilElement {
    }
    var HTMLFlexContainerElement: {
        prototype: HTMLFlexContainerElement;
        new (): HTMLFlexContainerElement;
    };
    interface HTMLTextInputElement extends Components.TextInput, HTMLStencilElement {
    }
    var HTMLTextInputElement: {
        prototype: HTMLTextInputElement;
        new (): HTMLTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "auto-complete": HTMLAutoCompleteElement;
        "flex-container": HTMLFlexContainerElement;
        "text-input": HTMLTextInputElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
        "setState"?: () => any;
        "state"?: any;
    }
    interface AutoComplete {
        "label"?: string;
        "onPick"?: (event: CustomEvent<string>) => void;
        "options"?: string;
        "required"?: boolean;
        "selected"?: string;
    }
    interface FlexContainer {
        "gap"?: string;
    }
    interface TextInput {
        "label"?: string;
        "name"?: string;
        "onInputChange"?: (event: CustomEvent<string>) => void;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "auto-complete": AutoComplete;
        "flex-container": FlexContainer;
        "text-input": TextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "auto-complete": LocalJSX.AutoComplete & JSXBase.HTMLAttributes<HTMLAutoCompleteElement>;
            "flex-container": LocalJSX.FlexContainer & JSXBase.HTMLAttributes<HTMLFlexContainerElement>;
            "text-input": LocalJSX.TextInput & JSXBase.HTMLAttributes<HTMLTextInputElement>;
        }
    }
}
